package mkn;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import lombok.AllArgsConstructor;

@Component
@AllArgsConstructor
public class PizzaApplicationRunner implements ApplicationRunner {
	private final PizzaRepository repository;
	private final JdbcTemplate jdbcTemplate;
	
	@Override
	public void run(final ApplicationArguments args) throws Exception {
		final String sql = """
		   create table pizza (
				id bigint generated by default as identity, 
				z_name varchar(255) unique, 
				type varchar(255), 
				primary key (id))
		   """;
		
		jdbcTemplate.execute(sql);

		repository.save(new Pizza().setType("pepperoni").setName("Marks-Pepperoni"));
	    repository.save(new Pizza().setType("supreme").setName("Mark's Supreme"));
	    repository.save(new Pizza().setType("pepperoni").setName("Bob's Pepperoni"));
	    repository.findAll().forEach(System.out::println);
	    
	    repository.findByName("Mark's Supreme").forEach(System.out::println);
	    repository.findByType("pepperoni").forEach(System.out::println);
	}

}
